[package]
name = "go_gc"
version = "0.1.0"
authors = ["Tinco Andringa <mail@tinco.nl>"]
edition = '2018'

[dependencies]
futures = "0.1.24"
futures_future = "0.1"
cache_line_size = "0.2"
array-init = "0"
